name: kubernetes-deploy

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      manifests:
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  k8s-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: ${{ inputs.namespace }}
          manifests: ${{ inputs.manifests }}
